stages:
  - stylecheck
  - build
  - test

checkstyle:
  stage: stylecheck
  image: $CI_REGISTRY/abgabesystem/checkstyle:latest

  tags:
    - stylecheck

  script:
    - Dummy Script 

build:
  stage: build

  tags:
    - gradle
    - build

  image: gradle:jdk8

  script:
    - gradle build

test:
  stage: test
  image: gradle:jdk8

  tags:
    - gradle
    - test

  script:
    - gradle test
